name: CRM CI/CD Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Optional: Install dependencies and build if needed
      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests and generate coverage (if using Jest)
      #   run: npm run test -- --coverage
      # Ensure this creates "coverage/lcov.info"

      # ---------- FOSSA ----------
      - name: Set up FOSSA CLI v3
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          echo "$HOME/.fossa/bin" >> $GITHUB_PATH

      - name: Run FOSSA Scan (Full Access)
        run: |
          fossa analyze
          fossa test
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        continue-on-error: true


      # ---------- Snyk ----------
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v1
        continue-on-error: true  # Optional: allow build to continue on Snyk failure
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # # ---------- StackHawk ----------
      # - name: Run StackHawk Scan
      #   uses: stackhawk/hawkscan-action@v2
      #   with:
      #     apiKey: ${{ secrets.STACKHAWK_API_KEY }}
      #     applicationId: 9a084eae-b00e-443a-8a0a-7e095fc9f52a


      # --- SONARCLOUD ANALYSIS STEP START ---
      - name: Set up Java (required by SonarCloud)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=SumitChourey-CN_CRM-Frontend
            -Dsonar.organization=sumitchourey-cn
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # --- SONARCLOUD ANALYSIS STEP END ---

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1

      # - name: Deploy static site to S3 bucket
      #   run: aws s3 sync . s3://crm-cloudnexus --delete
